# -*- coding: utf-8 -*-
"""NM Assignment 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QbH4381KkyYD1dITx9cbnRvNNghQ9qjS
"""

!pip install pandas

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import re
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()



df = pd.read_csv("/content/CAR DETAILS FROM CAR DEKHO.csv")
print(df)

print(df.info())
print('-' * 40)
print(df.info())

df.describe()

df.info()

df.isnull().sum()

sns.histplot(df["selling_price"])

sns.boxplot(x="year",y="selling_price",data=df)
plt.xticks(rotation=90)
plt.show()

sns.countplot(df["year"])
plt.xticks(rotation=90)
plt.show()

sns.scatterplot(x="fuel",y="selling_price",data=df)

sns.heatmap(df.corr(),annot=True)

df[["km_driven"]]=scaler.fit_transform(df[["km_driven"]])

df[["km_driven"]]

df["fuel"]=encoder.fit_transform(df["fuel"])

df["fuel"]

df["seller_type"]=encoder.fit_transform(df["seller_type"])
df["transmission"]=encoder.fit_transform(df["transmission"]) 
df["owner"]=encoder.fit_transform(df["owner"])

x=df.drop(["selling_price"],axis=1)
y=df["selling_price"]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=42)

print(f"x train shape: {x_train.shape}")
print(f"x test shape: {x_test.shape}")
print(f"y train shape: {y_train.shape}")
print(f"y test shape: {y_test.shape}")